# List of English words for the game

english_words = [
    "PHYTON",
    "ROYAL",
    "JUBILEE",
    "PARTY",
    "ABOUT",
    "MAGIC",
    "MARKET",
    "DIRECT",
    "WEATHER",
    "REGISTER",
    "ABSOLUTE",
    "ACROSS",
    "BEHIND",
    "BESIDE",
    "CITIZEN",
    "CLINICAL",
    "DEFINE",
    "DISCOVER",
    "DIVERSE",
    "EMOTION",
    "FITNESS",
    "GENETIC",
    "HORIZON",
    "MECHANISM",
    "WHISPER",
    "WITNESS",
    "UNLIKE",
    "TRADITION",
    "THEORY",
    "SOUTHERN",
    "ADVANCE",
    "DESIGNER",
    "FAITH",
]

# List of Spanish words for the game

spanish_words = [
    "TAREA",
    "SOLEADO",
    "PLAYA",
    "COMER",
    "FIESTA",
    "AHORA",
    "PAELLA",
    "TINTO",
    "COCHE",
    "LONDRES",
    "BROMA",
    "PAREJA",
    "VERDURAS",
    "PLANES",
    "VUELTA",
    "INTENTAR",
    "COMIDA",
    "HABLAR",
    "PERDER",
    "GANAR",
    "FORMAL",
    "PROVECHO",
    "LUEGO",
    "VIAJE",
    "AGOSTO",
    "MINUTO",
    "HERMANO",
    "ABRAZO",
    "JOVEN",
    "CONTENTO",
    "MUSEO",
    "GUSTAR",
    "ESTUDIAR",
]

# List of French words for the game

french_words = [
    "GLACIER",
    "FEMME",
    "TEMPS",
    "MONDE",
    "MONSIEUR",
    "RAISON",
    "BEAU",
    "SAVOIR",
    "BONHEUR",
    "VOITURE",
    "CHANSON",
    "PARDON",
    "TROUVE",
    "TOURNEZ",
    "DESCENDS",
    "COMBIEN",
    "TAILLE",
    "PRENDS",
    "ENFANTS",
    "SOEUR",
    "LIVRE",
    "MANCHETTE",
    "CRITIQUE",
    "ALMANACH",
    "CURSEUR",
    "MONTAGNE",
    "ACIDES",
    "PISCINE",
    "EXERCISE",
    "CORDE",
    "CHAUSSER",
    "TRAVAIL",
    "VAISSELLE",
]